module Stream

    using Rocket
    using ..Config
    using ..Simulator

    @doc """
        Stream

    A module for managing reactive sensor data streams.

    This module provides `SensorStream`, a structure to encapsulate a reactive data stream generated by `Simulator.jl`, and functions to create and access the stream.

    # Exports
    - `SensorStream`: A structure representing a sensor data stream.
    - `make_stream`: Creates a stream from a `SensorConfig`.
    - `get_observable`: Retrieves the observable from a stream.
    """

    export SensorStream, make_stream, get_observable

    @doc """
        SensorStream

    A structure that encapsulates a reactive data stream for sensor readings.

    # Fields
    - `source::Rocket.Subscribable{Float64}`: The underlying observable emitting sensor readings.
    """
    struct SensorStream
        source::Rocket.Subscribable{Float64}
    end

    @doc """
        make_stream(cfg::SensorConfig) -> SensorStream

    Creates a reactive data stream from a sensor configuration.

    # Parameters
    - `cfg::SensorConfig`: Configuration for the sensor, including frequency, noise, and base signal.

    # Returns
    - A `SensorStream` wrapping the observable that emits sensor readings.

    # Examples
    ```julia
    cfg = SensorConfig("temp", 100.0, 0.1, t -> 25 + sin(t))
    stream = make_stream(cfg)
    ```
    """
    function make_stream(cfg::SensorConfig)
        SensorStream(make_sensor_source(cfg))
    end

    @doc """
        get_observable(stream::SensorStream) -> Rocket.Subscribable{Float64}

    Retrieves the underlying observable from a sensor stream.

    # Parameters
    - `stream::SensorStream`: The sensor stream.

    # Returns
    - The `Rocket.Subscribable{Float64}` emitting sensor readings.

    # Examples
    ```julia
    cfg = SensorConfig("temp", 100.0, 0.1, t -> 25 + sin(t))
    stream = make_stream(cfg)
    subscribe!(get_observable(stream), x -> println(x))
    ```
    """
    function get_observable(stream::SensorStream)
        stream.source
    end
end